CREATE TABLE kanaSystem (
kns_ID integer primary key autoincrement,
kns_hiragana nvarchar(255),
kns_katakana nvarchar(255),
kns_romaji varchar(255)
); 

INSERT INTO kanaSystem
VALUES 
(NULL, 'あ','ア','a'),
(NULL, 'い','イ','i'),
(NULL, 'う','ウ',''),
(NULL,'え','エ','e'),
(NULL,'お','オ','o'),
(NULL,'か','カ','ka'),
(NULL,'き','キ','ki'),
(NULL,'く','ク','k'),
(NULL,'け','ケ','ke'),
(NULL,'こ','コ','ko'),
(NULL,'さ','サ','sa'),
(NULL,'し','シ','shi'),
(NULL,'す','ス','s'),
(NULL,'せ','セ','se'),
(NULL,'そ','ソ','so'),
(NULL,'た','タ','ta'),
(NULL,'ち','チ','chi'),
(NULL,'つ','ツ','ts'),
(NULL,'て','テ','te'),
(NULL,'と','ト','to'),
(NULL,'な','ナ','na'),
(NULL,'に','ニ','ni'),
(NULL,'ぬ','ヌ','n'),
(NULL,'ね','ネ','ne'),
(NULL,'の','ノ','no'),
(NULL,'は','ハ','ha'),
(NULL,'ひ','ヒ','hi'),
(NULL,'ふ','フ','f'),
(NULL,'へ','ヘ','he'),
(NULL,'ほ','ホ','ho'),
(NULL,'ま','マ','ma'),
(NULL,'み','ミ','mi'),
(NULL,'む','ム','m'),
(NULL,'め','メ','me'),
(NULL,'も','モ','mo'),
(NULL,'や','ヤ','ya'),
(NULL,'ゆ','ユ','y'),
(NULL,'よ','ヨ','yo'),
(NULL,'ら','ラ','ra'),
(NULL,'り','リ','ri'),
(NULL,'る','ル','r'),
(NULL,'れ','レ','re'),
(NULL,'ろ','ロ','ro'),
(NULL,'わ','ワ','wa'),
(NULL,'を','ヲ','wo'),
(NULL,'ん','ン','n'),
(NULL,'が','ガ','ga'),
(NULL,'ぎ','ギ','gi'),
(NULL,'ぐ','グ','g'),
(NULL,'げ','ゲ','ge'),
(NULL,'ご','ゴ','go'),
(NULL,'ざ','ザ','za'),
(NULL,'じ','ジ','ji'),
(NULL,'ず','ズ','z'),
(NULL,'ぜ','ゼ','ze'),
(NULL,'だ','ダ','da'),
(NULL,'で','デ','de'),
(NULL,'ど','ド','do'),
(NULL,'ば','バ','ba'),
(NULL,'び','ビ','bi' ),
(NULL,'ぶ','ブ','b'),
(NULL,'べ','ベ','be'),
(NULL,'ぼ','ボ','bo'),
(NULL,'ば','パ','pa'),
(NULL,'ぴ','ピ','pi'),
(NULL,'ぷ','プ','p'),
(NULL,'ぺ','ペ','pe'),
(NULL,'ぽ','ポ','po'),
(NULL,'きゃ','キャ','kya'),
(NULL,'きゅ','キュ','ky'),
(NULL,'きょ','キョ','kyo'),
(NULL,'しゃ','シャ','sha'),
(NULL,'しゅ','シュ','sh'),
(NULL,'しょ','ショ','sho'),
(NULL,'ちゃ','チャ','cha'),
(NULL,'ちゅ','チュ','ch'),
(NULL,'ちょ','チョ','cho'),
(NULL,'にゃ','ニャ','nya'),
(NULL,'にゅ','ニュ','ny'),
(NULL,'にょ','ニョ','nyo'),
(NULL,'ひゃ','ヒャ','hya'),
(NULL,'ひゅ','ヒュ','hy'),
(NULL,'ひょ','ヒョ','hyo'),
(NULL,'みゃ','ミャ','mya'),
(NULL,'みゅ','ミュ','my'),
(NULL,'みょ','ミョ','myo'),
(NULL,'りゃ','リャ','rya'),
(NULL,'りゅ','リュ','ry'),
(NULL,'りょ','リョ','ryo'),
(NULL,'ぎゃ','ギャ','gya'),
(NULL,'ぎゅ','ギュ','gy'),
(NULL,'ぎょ','ギョ','gyo'),
(NULL,'じゃ','ジャ','ja'),
(NULL,'じゅ','ジュ','j'),
(NULL,'じょ','ジョ','jo'),
(NULL,'びゃ','ビャ','bya'),
(NULL,'びゅ','ビュ','by'),
(NULL,'びょ','ビョ','byo'),
(NULL,'ぴゃ','ピャ','pya'),
(NULL,'ぴゅ','ピュ','py'),
(NULL,'ぴょ','ピョ','pyo'),
(NULL, 'っ','ッ','xts'),
(NULL,'ふぁ','ファ','fa');


