CREATE TABLE kanaSystem (
kns_ID integer primary key autoincrement,
kns_hiragana nvarchar(255),
kns_katakana nvarchar(255),
kns_romaji varchar(255)
); 

INSERT INTO kanaSystem
VALUES 
(NULL, u'あ',u'ア','a'),
(NULL, u'い',u'イ','i'),
(NULL, u'う',u'ウ','u'),
(NULL,u'え',u'エ','e'),
(NULL,u'お',u'オ','o'),
(NULL,u'か',u'カ','ka'),
(NULL,u'き',u'キ','ki'),
(NULL,u'く',u'ク','ku'),
(NULL,u'け',u'ケ','ke'),
(NULL,u'こ',u'コ','ko'),
(NULL,u'さ',u'サ','sa'),
(NULL,u'し',u'シ','shi'),
(NULL,u'す',u'ス','su'),
(NULL,u'せ',u'セ','se'),
(NULL,u'そ',u'ソ','so'),
(NULL,u'た',u'タ','ta'),
(NULL,u'ち',u'チ','chi'),
(NULL,u'つ',u'ツ','tsu'),
(NULL,u'て',u'テ','te'),
(NULL,u'と',u'ト','to'),
(NULL,u'な',u'ナ','na'),
(NULL,u'に',u'ニ','ni'),
(NULL,u'ぬ',u'ヌ','nu'),
(NULL,u'ね',u'ネ','ne'),
(NULL,u'の',u'ノ','no'),
(NULL,u'は',u'ハ','ha'),
(NULL,u'ひ',u'ヒ','hi'),
(NULL,u'ふ',u'フ','fu'),
(NULL,u'へ',u'ヘ','he'),
(NULL,u'ほ',u'ホ','ho'),
(NULL,u'ま',u'マ','ma'),
(NULL,u'み',u'ミ','mi'),
(NULL,u'む',u'ム','mu'),
(NULL,u'め',u'メ','me'),
(NULL,u'も',u'モ','mo'),
(NULL,u'や',u'ヤ','ya'),
(NULL,u'ゆ',u'ユ','yu'),
(NULL,u'よ',u'ヨ','yo'),
(NULL,u'ら',u'ラ','ra'),
(NULL,u'り',u'リ','ri'),
(NULL,u'る',u'ル','ru'),
(NULL,u'れ',u'レ','re'),
(NULL,u'ろ',u'ロ','ro'),
(NULL,u'わ',u'ワ','wa'),
(NULL,u'を',u'ヲ','wo'),
(NULL,u'ん',u'ン','n'),
(NULL,u'が',u'ガ','ga'),
(NULL,u'ぎ',u'ギ','gi'),
(NULL,u'ぐ',u'グ','gu'),
(NULL,u'げ',u'ゲ','ge'),
(NULL,u'ご',u'ゴ','go'),
(NULL,u'ざ',u'ザ','za'),
(NULL,u'じ',u'ジ','ji'),
(NULL,u'ず',u'ズ','zu'),
(NULL,u'ぜ',u'ゼ','ze'),
(NULL,u'だ',u'ダ','da'),
(NULL,u'で',u'デ','de'),
(NULL,u'ど',u'ド','do'),
(NULL,u'ば',u'バ','ba'),
(NULL,u'び',u'ビ','bi' ),
(NULL,u'ぶ',u'ブ','bu'),
(NULL,u'べ',u'ベ','be'),
(NULL,u'ぼ',u'ボ','bo'),
(NULL,u'ば',u'パ','pa'),
(NULL,u'ぴ',u'ピ','pi'),
(NULL,u'ぷ',u'プ','pu'),
(NULL,u'ぺ',u'ペ','pe'),
(NULL,u'ぽ',u'ポ','po'),
(NULL,u'きゃ',u'キャ','kya'),
(NULL,u'きゅ',u'キュ','kyu'),
(NULL,u'きょ',u'キョ','kyo'),
(NULL,u'しゃ',u'シャ','sha'),
(NULL,u'しゅ',u'シュ','shu'),
(NULL,u'しょ',u'ショ','sho'),
(NULL,u'ちゃ',u'チャ','cha'),
(NULL,u'ちゅ',u'チュ','chu'),
(NULL,u'ちょ',u'チョ','cho'),
(NULL,u'にゃ',u'ニャ','nya'),
(NULL,u'にゅ',u'ニュ','nyu'),
(NULL,u'にょ',u'ニョ','nyo'),
(NULL,u'ひゃ',u'ヒャ','hya'),
(NULL,u'ひゅ',u'ヒュ','hyu'),
(NULL,u'ひょ',u'ヒョ','hyo'),
(NULL,u'みゃ',u'ミャ','mya'),
(NULL,u'みゅ',u'ミュ','myu'),
(NULL,u'みょ',u'ミョ','myo'),
(NULL,u'りゃ',u'リャ','rya'),
(NULL,u'りゅ',u'リュ','ryu'),
(NULL,u'りょ',u'リョ','ryo'),
(NULL,u'ぎゃ',u'ギャ','gya'),
(NULL,u'ぎゅ',u'ギュ','gyu'),
(NULL,u'ぎょ',u'ギョ','gyo'),
(NULL,u'じゃ',u'ジャ','ja'),
(NULL,u'じゅ',u'ジュ','ju'),
(NULL,u'じょ',u'ジョ','jo'),
(NULL,u'びゃ',u'ビャ','bya'),
(NULL,u'びゅ',u'ビュ','byu'),
(NULL,u'びょ',u'ビョ','byo'),
(NULL,u'ぴゃ',u'ピャ','pya'),
(NULL,u'ぴゅ',u'ピュ','pyu'),
(NULL,u'ぴょ',u'ピョ','pyo'),
(NULL, u'っ',u'ッ','xtsu'),
(NULL,u'ふぁ',u'ファ','fa');


